export const state = {
  db: null,
  conn: null,
  dataTableReady: false,
  rows: [],
  products: [],
  weeks: [],
  filters: {
    week: "ALL",
    dateStart: "",
    dateEnd: "",
    products: new Set(),
  },
  bounds: {
    minDate: "",
    maxDate: "",
  },
  table: {
    page: 1,
    pageSize: 10,
    sortBy: "revenue",
    sortDir: "desc",
  },
  charts: {
    units: null,
    discount: null,
    margin: null,
    revenue: null,
  },
  activeSourceName: "",
  defaultDataDir: "../data/",
  defaultFallbackCsv: "../data/shopify_profitability.csv",
};

export const UI_ELEMENTS = {
  status: document.getElementById("status"),
  weekSelect: document.getElementById("weekSelect"),
  dateStart: document.getElementById("dateStart"),
  dateEnd: document.getElementById("dateEnd"),
  productSelect: document.getElementById("productSelect"),
  fileInput: document.getElementById("fileInput"),
  resetFiltersBtn: document.getElementById("resetFiltersBtn"),
  kpiUnits: document.getElementById("kpiUnits"),
  kpiRevenue: document.getElementById("kpiRevenue"),
  kpiRevenueWeekly: document.getElementById("kpiRevenueWeekly"),
  kpiRevenueEx: document.getElementById("kpiRevenueEx"),
  kpiRevenueWeeklyEx: document.getElementById("kpiRevenueWeeklyEx"),
  kpiMargin: document.getElementById("kpiMargin"),
  kpiDiscountRate: document.getElementById("kpiDiscountRate"),
  kpiTopSellerLabel: document.getElementById("kpiTopSellerLabel"),
  kpiTopSeller: document.getElementById("kpiTopSeller"),
  kpiTopSellerSub: document.getElementById("kpiTopSellerSub"),
  kpiMostProfitableLabel: document.getElementById("kpiMostProfitableLabel"),
  kpiMostProfitable: document.getElementById("kpiMostProfitable"),
  kpiMostProfitableSub: document.getElementById("kpiMostProfitableSub"),
  tableBody: document.getElementById("tableBody"),
  tableMeta: document.getElementById("tableMeta"),
  pageInfo: document.getElementById("pageInfo"),
  prevPageBtn: document.getElementById("prevPageBtn"),
  nextPageBtn: document.getElementById("nextPageBtn"),
  chart1Title: document.getElementById("chart1Title"),
  chart2Title: document.getElementById("chart2Title"),
};
